Document: python-cfengine
Title: Debian python-cfengine Manual
Author: <insert document author here>
Abstract: This manual describes what python-cfengine is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/python-cfengine/python-cfengine.sgml.gz

Format: postscript
Files: /usr/share/doc/python-cfengine/python-cfengine.ps.gz

Format: text
Files: /usr/share/doc/python-cfengine/python-cfengine.text.gz

Format: HTML
Index: /usr/share/doc/python-cfengine/html/index.html
Files: /usr/share/doc/python-cfengine/html/*.html
