#!/usr/bin/python

import pwd
import cfengine3

if __name__ == '__main__':

    cf3 = cfengine3.protocol()
    users = [ user[0] for user in  pwd.getpwall() ]
    cf3.classes('system_users','define')
    cf3.scalar('count', '%s' % len(users))
    cf3.list('users', users)
